[package]
name = "resonanse_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = "0.7.2"
chrono = "0.4"
uuid = "1.4"