version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  resonanse_bot:
    depends_on:
      - postgres
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./tg_downloads:/app/tg_downloads
    env_file:
      - conf.env
    restart: always
